# 2023.11.28 - 에러를 잡아서 테스트하기

테스트커버리지를 확인하면서 테스트를 빠트린 코드가 있는지 확인하는중이다. 테스트 커버리지가 높다고 완벽한 테스트인것은 아닐테지만, 테스트가 처음이자 적당한 가이드라인이 없는 상황에서는

한개의 기준이 되어주고있어 아주 고마워하고 있다. ;]

![Untitled](../../Picture/diary1.png)

한번 쭉 테스트 코드를 작성하고 실행해본 커버리지. if에 대한 테스트가 많이 빠져있었다!

### 테스트 커버리지 올리기

테스트가 되고 있지 않은 코드까지 함께 보여줘서 검토하기에 매우 효과적이었다.
그런데 try catch문의 throw error 부분이 expect().toTrowError로 되지 않는것..!

### expect().reject.toThrowError('~') 사용하기

테스트 실행결과를 보았을때, service의 throw error 메세지는 잘 던져지고있지만, 그것을 expect().toTrowError('~')에서 잡지 못하는것 처럼 보였다. 함수는 올바른 값을 반환하지만 반환된 값이 맞는지 확인하기전에 테스트가 종료되는것이다.

여기서 expect.matcher부분을 어떻게 비동기로 실행해줘야할지 고민이었는데,

```typescript
await expect(service.function()).rejects.toThrowError("message");
```

이렇게 작성해주면된다. await으로 비동기 처리를 하고, rejects를 사용해서 에러를 잡아 처리할 수 있다.

## ![Untitled](../../Picture/diary2.png)

### 정리

- expect.rejects.toThrowError는 Jest에서 비동기 코드에서 발생하는 에러를 테스트하기위한 메소드이다.
- 이 메서드를 사용하면 비동기 함수가 reject되고 올바른 에러메시지를 가지고 있는지 테스트 할 수 있다.
- expect 에 함수를 전달하고, reject는 전달된 함수의 promise가 reject 상태인지 학인한다. 이후 .toThrowError를 호출하여 예상한 에러인지 확인한다.
- reject 상태가 되었을때 에러메세지를 검사할 수 있는 matcher이다.

